import tkinter 
from tkinter import messagebox
root=tkinter.Tk()
def hellocallback():
    messagebox.showinfo("hello python","hello world")
B1=tkinter.Button(root,text="1.Anoop",command=hellocallback)
B2=tkinter.Button(root,text="2.Shivam",command=hellocallback)
B3=tkinter.Button(root,text="3.Anurag",command=hellocallback)
B4=tkinter.Button(root,text="4.Sanbarto",command=hellocallback)
B5=tkinter.Button(root,text="5.Dheeraj",command=hellocallback)
B6=tkinter.Button(root,text="6.Yadu",command=hellocallback)
B7=tkinter.Button(root,text="7.Shivi",command=hellocallback)
B8=tkinter.Button(root,text="8.Srawan",command=hellocallback)
B9=tkinter.Button(root,text="9.Reshma",command=hellocallback)
B10=tkinter.Button(root,text="10.Riya",command=hellocallback)
B11=tkinter.Button(root,text="11.Ishita",command=hellocallback)
B12=tkinter.Button(root,text="12.Priya",command=hellocallback)
B13=tkinter.Button(root,text="13.Mehek",command=hellocallback)
B14=tkinter.Button(root,text="14.Disha",command=hellocallback)
B15=tkinter.Button(root,text="15.Kanika",command=hellocallback)
B1.pack()
B2.pack()
B3.pack()
B4.pack()
B5.pack()
B6.pack()
B7.pack()
B8.pack()
B9.pack()
B10.pack()
B11.pack()
B12.pack()
B13.pack()
B14.pack()
B15.pack()
root.mainloop()



